appVersion: v0.5.0
description: Installs the node-problem-detector daemonset for monitoring extra attributes
  on nodes
engine: gotpl
home: https://github.com/kubernetes/node-problem-detector
icon: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png
keywords:
- node
- problem
- detector
- monitoring
maintainers:
- email: max.williams@deliveryhero.com
  name: max-rocket-internet
name: node-problem-detector
sources:
- https://github.com/kubernetes/charts/stable/node-problem-detector
- https://github.com/kubernetes/node-problem-detector
- https://kubernetes.io/docs/concepts/architecture/nodes/#condition
version: "1.0"
