apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-dynamic-class"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

