apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-envoy-admin-ingress
  namespace: default
spec:
  rules:
  - host: myapp-envoy-admin.k8s.io
    http:
      paths:
      - path: /
        backend:
          serviceName: myapp-envoy
          servicePort: 9901

