apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana
    chart: grafana-1.10.0
    heritage: Tiller
    release: grafana
  name: grafana
  selfLink: /api/v1/namespaces/monitoring/services/grafana
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
    release: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
