apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
    chart: prometheus-6.7.0
    component: alertmanager
    heritage: Tiller
    release: monitor
  name: monitor-prometheus-alertmanager
  selfLink: /api/v1/namespaces/monitoring/services/monitor-prometheus-alertmanager
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9093
  selector:
    app: prometheus
    component: alertmanager
    release: monitor
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
