apiVersion: v1
data:
  alertmanager.yml: |
    global:
      smtp_auth_password: '*********'
      smtp_auth_username: xxxx@163.com
      smtp_from: xxxx@163.com
      smtp_require_tls: false
      smtp_smarthost: smtp.163.com:25
    receivers:
    - email_configs:
      - to: xxxx@163.com
      name: AlertMail
    route:
      group_by:
      - alertname
      - pod_name
      group_interval: 5m
      group_wait: 10s
      receiver: AlertMail
      repeat_interval: 3h
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
    chart: prometheus-6.7.0
    component: alertmanager
    heritage: Tiller
    release: monitor
  name: monitor-prometheus-alertmanager
  selfLink: /api/v1/namespaces/monitoring/configmaps/monitor-prometheus-alertmanager
