apiVersion: v1
kind: Endpoints
metadata:
  labels:
    k8s-app: etcd
  name: etcd-k8s
  namespace: kube-system
subsets:
- addresses:
  - ip: 192.168.2.11
    targetRef:
      kind: Node
      name: 192.168.2.11
  - ip: 192.168.2.12
    targetRef:
      kind: Node
      name: 192.168.2.12
  - ip: 192.168.2.13
    targetRef:
      kind: Node
      name: 192.168.2.13
  ports:
  - name: port
    port: 2379
    protocol: TCP
