FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

RUN echo '<html><body><p>This application is <strong style="color: green;">GREEN</strong>.</body></html>' > /usr/share/nginx/html/index.html \
  &&  echo 'OK' > /usr/share/nginx/html/healthy.html
