kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: office-namespace-admin
  namespace: office
subjects:
- kind: ServiceAccount
  name: default
  namespace: office
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
