apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: psp.traefik.unprivileged
spec:
  privileged: true
  volumes:
    - configMap
    - secret
    - hostPath
  readOnlyRootFilesystem: false
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  allowPrivilegeEscalation: true
  defaultAllowPrivilegeEscalation: true
  allowedCapabilities: ['NET_BIND_SERVICE']
  defaultAddCapabilities: []
  requiredDropCapabilities: []
  hostPID: true
  hostIPC: true
  hostNetwork: false
  hostPorts:
  - max: 65535
    min: 0
  seLinux:
    rule: 'RunAsAny'
