apiVersion: v1
kind: Service
metadata:
  name: myapp-without-hook
  namespace: default
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp-without-hook
  sessionAffinity: None
  type: NodePort
