apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp-without-hook
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: myapp-without-hook
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: 314315960/zero-downtime-tutorial:green
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 80
