apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: kube-system
spec:
  containers:
  - name: kubewatch
    image: bitnami/kubewatch
    imagePullPolicy: Always    
    volumeMounts:
    - name: config-volume
      mountPath: /opt/bitnami/kubewatch/.kubewatch.yaml
      subPath: .kubewatch.yaml
  restartPolicy: Always
  serviceAccountName: kubewatch
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch
