apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "default"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
