apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  labels:
    app: redis
    appCluster: redis-cluster
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: gossip
    port: 16379
    targetPort: 16379
  clusterIP: None
  selector:
    appCluster: redis-cluster
